// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Project_NZWalks.API.Data;

#nullable disable

namespace Project_NZWalks.API.Migrations
{
    [DbContext(typeof(NZWalksDbContext))]
    [Migration("20260624095546_Seeding data of Region and Difficulty")]
    partial class SeedingdataofRegionandDifficulty
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Project_NZWalks.API.Models.Domain.Difficulty", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Difficulties");

                    b.HasData(
                        new
                        {
                            Id = new Guid("0561b51f-cf84-4d5b-ba9a-b01b015d767d"),
                            Name = "Easy"
                        },
                        new
                        {
                            Id = new Guid("d221c450-9ebf-48b2-9689-e8bb848cd706"),
                            Name = "Medium"
                        },
                        new
                        {
                            Id = new Guid("56078d10-f920-4387-8ff1-36a824f0f335"),
                            Name = "Hard"
                        });
                });

            modelBuilder.Entity("Project_NZWalks.API.Models.Domain.Region", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RegionImageURL")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Regions");

                    b.HasData(
                        new
                        {
                            Id = new Guid("f3a10e08-4238-451d-9845-a9df6529da77"),
                            Code = "AKL",
                            Name = "Auckland",
                            RegionImageURL = "auckland-image.jpg"
                        },
                        new
                        {
                            Id = new Guid("a38bd9dd-ff3a-4f82-a892-96497f41f0fb"),
                            Code = "WLG",
                            Name = "Wellington",
                            RegionImageURL = "wellington-image.jpg"
                        },
                        new
                        {
                            Id = new Guid("04ff1b15-e044-421d-9d1a-1e313095a17f"),
                            Code = "CAN",
                            Name = "Canterbury",
                            RegionImageURL = "canterbury-image.jpg"
                        },
                        new
                        {
                            Id = new Guid("60b97ace-086a-4c28-b662-31922701ef10"),
                            Code = "OTA",
                            Name = "Otago",
                            RegionImageURL = "otago-image.jpg"
                        },
                        new
                        {
                            Id = new Guid("29b26514-dbb1-4a38-96eb-28f08ba2fd34"),
                            Code = "WKT",
                            Name = "Waikato",
                            RegionImageURL = "waikato-image.jpg"
                        },
                        new
                        {
                            Id = new Guid("7032e402-dfbc-4419-8609-0e3918f1c78d"),
                            Code = "BOP",
                            Name = "Bay of Plenty",
                            RegionImageURL = "bayofplenty-image.jpg"
                        });
                });

            modelBuilder.Entity("Project_NZWalks.API.Models.Domain.Walk", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("DifficultyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("LengthInKM")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RegionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("WalkImageURL")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DifficultyId");

                    b.HasIndex("RegionId");

                    b.ToTable("Walks");
                });

            modelBuilder.Entity("Project_NZWalks.API.Models.Domain.Walk", b =>
                {
                    b.HasOne("Project_NZWalks.API.Models.Domain.Difficulty", "Difficulty")
                        .WithMany()
                        .HasForeignKey("DifficultyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Project_NZWalks.API.Models.Domain.Region", "Region")
                        .WithMany()
                        .HasForeignKey("RegionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Difficulty");

                    b.Navigation("Region");
                });
#pragma warning restore 612, 618
        }
    }
}
